spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library_db
    username: library_user
    password: library_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

security:
  jwt:
    secret: ZGV2c2VjcmV0LWRldnNlY3JldC1kZXZzZWNyZXQtZGV2c2VjcmV0LWRldnNlY3JldA==
    expiration-ms: 3600000
  cors:
    allowed-origins: http://localhost:3000
  require-https: false
